In [1]:
import numpy as np
import os


def load_data(file_name):
    dataMat = []
    labelMat = []
    fr = open(file_name)
    for line in fr.readlines()[1:]:
        line = line.strip().split()
        dataMat.append([line[0], line[1], ' '.join(line[2:-1])])
        labelMat.append(line[-1])
    return dataMat, labelMat


def create_dic(dataMat):
    Dict = []
    for line in dataMat:
        line = line[2].split()
        for element in line:
            if element not in Dict and element not in [',', '.']:
                Dict.append(element)
    return Dict


def create_vector(dict_, dataMat):
    m = len(dataMat)
    n = len(dict_)
    dataMatrix = np.zeros((m, n))
    for i in range(m):
        line = dataMat[i][2].strip().split()
        for word in line:
            if word not in dict_:
                continue
            if word not in [',', '.']:
                dataMatrix[i][dict_.index(word)] = 1
    return dataMatrix

In [2]:
def softmax(x_vector):
    exps = np.exp(x_vector)
    return exps / np.sum(exps)

In [3]:
def cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    """
    m = y.shape[0]
    for i in range(m):
        X[i] = softmax(X[i])
    #log_likelihood = -np.log(p[range(m),y])
    loss = X - y
    print(X)
    #loss = np.sum(log_likelihood) / m
    return loss


In [11]:
def gradAscent(dataMat, classLabels):
    dataMat = np.mat(dataMat)
    classLabels = np.mat(classLabels)
    m, n = np.shape(dataMat)
    # print(n, m)
    alpha = 0.01
    maxCycles = 2000
    weights = np.random.rand(n, 5)
    
    print(np.dot(dataMat, weights))

    for i in range(maxCycles):
        error = cross_entropy(np.dot(dataMat, weights), classLabels)
        weights -= alpha * np.dot(dataMat.transpose(), error)
        print(i, ': ', np.sum(error))



In [6]:
dataMat, labelMat = load_data('train.tsv')
labelMat = [int(x) for x in labelMat]
y = np.zeros((len(dataMat), 5))
for i in range(len(dataMat)):
    y[i][labelMat[i]-1] = 1
testMat, _ = load_data('test.tsv')
if os.path.exists('dict.txt'):
    fr = open('dict.txt', 'r')
    Dict = fr.readline().strip().split()
else:
    Dict = create_dic(dataMat)
    fw = open('dict.txt', 'w')
    fw.write(' '.join(Dict))


In [7]:
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [8]:
dataMatrix = create_vector(Dict, dataMat)
testMatrix = create_vector(Dict, testMat)

In [9]:
print(dataMatrix)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [13]:
print(len(dataMatrix),len(dataMatrix[0]), len(y))

156060 18224 156060


In [12]:
gradAscent(dataMatrix, y)

[[12.67000413 10.28916574 13.20754572 13.44419972 14.09846433]
 [ 7.76587631  5.25602603  6.35522489  7.03754744  7.01112961]
 [ 1.69168112  0.76203062  1.2399424   0.42366774  1.65259793]
 ...
 [ 1.76685218  1.54799362  0.74603087  1.31535243  1.25791263]
 [ 0.89338516  0.8216201   0.44242792  0.57864957  0.80911848]
 [ 0.87346702  0.72637352  0.30360295  0.73670286  0.44879415]]


KeyboardInterrupt: 